[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://ykdnaeltsrbiryrgytjk.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZG5hZWx0c3JiaXJ5cmd5dGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjk1MDIsImV4cCI6MjA1NzcwNTUwMn0._8y78hK9j6WcHtFj1-3vweeHDa16PZali8a_7lTjOmw"
